### PR TITLE
docs(lib): instruct user to have Angular CLI generate the routing

### PR DESCRIPTION
**Pull request by gerhardboer**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Other... Please describe: Documentation

## What is the current behavior?

Issue Number: https://github.com/scullyio/scully/issues/358

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by gerhardboer** [comment]
I've signed the CLA again, and the page says I have signed it.

However, the check still fails. Does it take a while to register?
Maybe something is wrong with my account ?

**Comment by jorgeucano** [comment]
hey @gerhardboer the assistant said
"You have signed the CLA already but the status is still pending? Let us recheck it."
Can you check in this link https://cla-assistant.io/check/scullyio/scully?pullRequest=381

**Comment by gerhardboer** [comment]
I've been trying multiple times, as well as signing into the cla-assitant.io website directly.
No idea why it still says not signed here.

image

**Comment by Villanuevand** [comment]
@jorgeucano  
@gerhardboer is right, he have been signed several times. 

Let's try with other option. Im going to remove your sign to the assitant.io

**Comment by Villanuevand** [comment]
@gerhardboer  / @jorgeucano 

I can't remove the sign, but  checking the issues in the CLA Assistent project and found [this issue](https://github.com/cla-assistant/cla-assistant/issues/528)

**Comment by gerhardboer** [comment]
@Villanuevand 
That might me it, i did commit the change from my work laptop which could have a different e-mail connected.
I'll check tonight on how to fix this

**Comment by Villanuevand** [comment]
@gerhardboer great!

**Comment by jorgeucano** [comment]
Hey i created a PR for this... thanks for your work @gerhardboer ... I don't know what happened with the CLA I will work on this...

**Pull request closed without merging**
