### PR TITLE
DRAFT: feat(schematics): add list page for markdown schematic

### PR DESCRIPTION
**Pull request by cmgriffing**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

## What is the current behavior?

The markdown schematic only scaffolds files needed for posts.

Issue Number: N/A

## What is the new behavior?

The markdown schematic scaffolds a list page along with the post code.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

This is an initial PR to feel out how this should be implemented. Creating a new set of templates and modifying the existing `markdown` schematic seems like the least amount of change to get the idea across.

I would be happy to refactor these changes to match more closely with what you would prefer after we have discussed the implementation details more. Tests and documentation updates would follow as needed, as well.

### CODE REVIEW

**Comment by jorgeucano** [comment]
@cmgriffing Hey I like the idea, but this is more one options into the markdown... I will add some comments into the code!

**Comment by jorgeucano** [comment]
We only need some lines from this file `files/markdown-with-list-page-module/page/__name@dasherize__-page.component.html.template`  and the option for "add the markdown with list"...

**Comment by cmgriffing** [comment]
I see what you mean about adding it to the schema.json. I can work on that.

I do think we still need the custom templates though.

- The module has to add both the page and post components to declarations.
- The routing module is slightly different than the original by adding an extra route for the list page.

**Comment by cmgriffing** [comment]
Update: I have added the option to the schema. I went with `includeListPage` as the prop name.

I have not changed the markdown yet. I wanted to change things incrementally just to make sure I am on the right track with what you are looking for.

**Comment by jorgeucano** [comment]
Hey now is better, I will add some task you need finish for this PR :) 

- [ ] remove the new template, only we need the list 
- [ ] remove the if into the functions (i add the comment)
- [ ] use this code into the original template
```
<% if (includeListPage) { %>
<div *ngFor="let <%= camelize(name) %>Post of <%= camelize(name) %>Posts">
  <a [routerLink]="<%= camelize(name) %>Post.route">{{ <%= camelize(name) %>Post.route }</a>
</div> 
<% } %>
```
- [ ] update the original test

**Comment by SanderElias** [comment]
@cmgriffing Are you going to fix the issues @jorgeucano listed?

**Comment by cmgriffing** [comment]
I'm just going to withdraw the PR.

A modified module and routing to support the list. I pointed that out previously and it was ignored.

I'm just going to create my own schematics for myself instead.

**Pull request closed without merging**
