### PR TITLE
feat(sully): prepare scully for running inside Docker container

### PR DESCRIPTION
**Pull request by beeman**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

## What is the current behavior?

Currently when running scully in a Docker container it fails with an error message similar to this:

```
Error: Failed to launch chrome! spawn /workspace/node_modules/puppeteer/.local-chromium/linux-706915/chrome-linux/chrome ENOENT
```

## What is the new behavior?

This PR adds the option to instruct Scully to use an existing chromium as executable, allowing it to run inside a Docker container.

It introduces support for the `SCULLY_PUPPETEER_EXECUTABLE_PATH` env var, if this is found it uses it's value as the `executablePath` for Puppeteer.

This allows for running Scully with a prepared Docker image, like [beeman/scully-docker](https://hub.docker.com/r/beeman/scully-docker).

After this patch, scully uses the browser that's pre-installed in the images and runs perfectly fine!

```
$ scully
Launching puppeteer with executablePath /usr/bin/chromium-browser
The option outFolder isn't configured, using default folder "/workspace/dist/static/".
Cleaned up /workspace/dist/static/ folder.
 ☺   new Angular build imported
started servers in background
servers available
Finding all routes in application.
Pull in data to create additional routes.
Finding files in folder "/workspace/blog"
Route list created in files:
      src/assets/scully-routes.json
      /workspace/dist/static/assets/scully-routes.json
Route "" rendered into file: "/workspace/dist/static/index.html"
Route "/blog/12-24-2019-blog" rendered into file: "/workspace/dist/static/blog/12-24-2019-blog/index.html"
Route "/about" rendered into file: "/workspace/dist/static/about/index.html"
Route list created in files:
      src/assets/scully-routes.json
      /workspace/dist/static/assets/scully-routes.json

Generating took 10.23 seconds for 3 pages:
  That is 0.3 pages per second,
  or 3412 milliseconds for each page.

Done in 21.09s.
```

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

Most of the information to build this feature comes from [here](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md).

### CODE REVIEW

**Comment by aaronfrost** [comment]
@beeman Can you please describe what the puppeteer options you added do to make this better prepared for Docker? I believe you but I want to learn what is going on in this PR.

**Comment by beeman** [comment]
@aaronfrost on our dev machines when installing `puppeteer` from npm it will download a recent version of Chromium. While this works great on most workstations, there are a situations (like CI or Docker) where Puppeteer can not download the right version. 

Take for instance a Docker images that's based on Alpine. In that case the solution is to prepare the Docker image and install chromium using that OS' package manager, and instruct Puppeteer to not download it (by setting the env var `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` to `true`) and point it to the locally installed chromium binary using the `executablePath` parameter when launching Puppeteer.

With this PR we can instruct Puppeteer that we want to change the `executablePath` and additionally when that's the case we add the argument `--disable-dev-shm-usage` as explained [here](https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md#tips).

Happy to elaborate more if needed!

**Comment by aaronfrost** [comment]
@beeman we need to update the commit when we get this merged. The commit says "feat(sully)" when it should have a C and say "feat(s__c__ully)".

**Comment by beeman** [comment]
@aaronfrost commit message is renamed
@SanderElias conflicts are resolved

**Pull request merged**
