### PR TITLE
fix(scully): make sure scully emits non-zero exit code on errors

### PR DESCRIPTION
**Pull request by beeman**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

## What is the current behavior?

Currently scully always emits a `0` as exit code, even when it fails. Emitting a non-zero exit code is essential if you want to use scully in an automated process, as it will halt the process if something fails - currently it just continues.

## What is the new behavior?

Emit exit code 5 ([Fatal exception](https://nodejs.org/api/process.html#process_exit_codes)) when something fails. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by SanderElias** [comment]
@beeman Thanks for the PR. 
This one was already on my radar, thanks for handling it.
However, error number 5 is in my view not suitable. the node documentation says: `There was a fatal unrecoverable error in V8` which is clearly not the case.

Can you change to `15`? As this is not being used by any node internals, it sends out a clear signal that it is something we do exit on deliberate. We might even refactor to a couple of different codes in te futue

**Comment by beeman** [comment]
@SanderElias just updated the PR to emit `15`

**Comment by aaronfrost** [comment]
@beeman what does a non-zero exit code do? I want to learn. Please teach me.

**Comment by beeman** [comment]
@aaronfrost this is relevant when we want to automate stuff, emitting a non-zero exit code from a child process will instruct the parent process to halt as something failed.

This is useful when you want to automate things in for instance a CI setup. There we want to execute all the steps, but we only want to continue with the next step if the current one successfully exits.

This is an example of `npm` emitting exit codes `0` or `1`:

```
➜  ~ npm install -g --silent @angular/cli
/usr/local/bin/ng -> /usr/local/lib/node_modules/@angular/cli/bin/ng
+ @angular/cli@8.3.21
updated 2 packages in 13.692s
➜  ~ echo $?
0
➜  ~ npm install -g --silent @angular/cli-this-does-not-work
➜  ~ echo $?
1
```

**Pull request merged**
