### PR TITLE
docs(showcase): add notiz.dev

### PR DESCRIPTION
**Pull request by marcjulian**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by SanderElias** [comment]
@marcjulian We have a big docs-refactor in PR. #753  Once this is done, we can merge this, but I suspect it might need some update

**Comment by marcjulian** [comment]
@SanderElias no problem, let me when the refactor is don then I can update it

**Comment by marcjulian** [comment]
@jorgeucano no worries :)

**Comment by jorgeucano** [comment]
https://scully.io/docs/community/showcase/ :)

**Pull request closed without merging**
