### PR TITLE
fix(ng-lib) normalize urlAfterRedirects before lastHandled comparison

### PR DESCRIPTION
**Pull request by jadengis**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

## What is the current behavior?
The url stored in `lastHandled` is normalized (fragments and queries removed). On NavigationEnd, this value is compared to `ev.urlAfterRedirects` which is not normalized and so `replaceContent` is called when it shouldn't be (routes to anchors on the same page).

Issue Number: #1350

## What is the new behavior?
Normalize `ev.urlAfterRedirects` before comparing to `lastHandled`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
I didn't see a spec for the ScullyContent component, so I'm not sure what the best way to test this is.

### CODE REVIEW

**Comment by SanderElias** [comment]
@jadengis Thanks for this PR. I think you are right and this is an oversight.
I would love it if there was a test added for this, so we can't regress on this in the future
The test should be [added here](https://github.com/scullyio/scully/blob/main/tests/cypress/integration/scullyContent.spec.js).

**Comment by jadengis** [comment]
@SanderElias I added a test to the file you indicated, and double checked that the test fails without the fix (obviously it passes with the fix). Let me know if there are any other changes required.

**Comment by jadengis** [comment]
@SanderElias Is there a problem with the build on `main`? I didn't touch anything relating to `js-yaml` but the build is failing with some type issue.

**Comment by SanderElias** [comment]
@jadengis we updated to V12, which has some stricter type checking. But main isn't failing. We can't merge failed builds.
I'll check out your branch and take a peek

**Comment by SanderElias** [comment]
Update, I have a couple of snapshots that fail on your branch, but everything builds fine locally.
 a test I created a new PR from yours #1361, that has the same changes. I'm not going to merge that, just checking what's hapening.

**Comment by jadengis** [comment]
Before the build failures, the snapshots for `blod-index.spec.ts` were failing (because I updated the sample blog) but those snaps should be updated in the PR since yesterday.

**Comment by SanderElias** [comment]
Ok, I figured this out.
What happened,
1, your PR being in the 'wait list'
2. Your PR created its own cache with all it needs.
3. I updated the main with V12
4. the changes don't affect your code, but do not work with cached content in your PR.

@Jefiozie Do you know if/how we can purge the cache on a pr?

**Comment by Jefiozie** [comment]
As far as I know we can't clear the cache manual. The cache is being made based on the package-lock when changed it will clear the cache. Second, The cache itself will be cleared after 7 days when not being used.

We could try to rebase the changes on the main branch. As the package-lock is changed in v12 this should trigger the cache. (I  think 😇)

**Comment by SanderElias** [comment]
@jadengis If you want to revive this PR, make a small change to the `/package.json` and do a push. that will invalidate the cache.
It is stupid, I know, but the only other alternative is to close this PR and creating a new one.

**Comment by jadengis** [comment]
Let me just open a new PR. That should be easy tbh.

**Comment by jadengis** [comment]
NVM seems like that doesn't work because it must be caching on the ref.

**Comment by SanderElias** [comment]
if you do `npm i @types/node` you will get a new package-lock, and all should start flowing again.
Sorry for this mess.

**Comment by jadengis** [comment]
I ran `npm i @types/node` and added the changes to this PR. Hopefully that works. :crossed_fingers:

**Comment by jadengis** [comment]
Hmm that didn't seem to work. I might just reimplement these changes from scratch in another branch. It's not a large changeset so it shouldn't be so bad.

**Comment by jadengis** [comment]
@SanderElias I've reimplemented these changes in a new branch with fresh commits in the hopes it will fix the build issues. I've opened this PR https://github.com/scullyio/scully/pull/1366 and will close this one in favour of that one.

**Pull request closed without merging**
