### PR TITLE
fix(scully): don't check  if launched from project folder

### PR DESCRIPTION
**Pull request by diminutivesloop**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

## What is the current behavior?
Scully checks whether it's running from a Scully project folder by comparing `__dirname` with `process.cwd()`. This breaks when the @scullyio/scully package is symlinked into the project dependencies since `__dirname` is resolved to the package symlink target location while `process.cwd()` returns the directory from which Scully was launched and where the symlink itself resides. This symlinking happens when using a tool such as [pnpm](https://pnpm.js.org/) to manage multiple projects in a monorepo and also when using `npm link` to install a locally modified copy of Scully into a test project during development. 

Issue Number: N/A

## What is the new behavior?
Scully no longer performs this check. Aside from enabling symlinked installation, this change also enables running Scully from sub-directories or in projects with hoisted dependencies such as those created by tools such as [Lerna](https://lerna.js.org/). 

If it's still important for Scully to only run in the root of a Scully project then we should consider verifying this in a way that doesn't present the issues described above such as checking for the presence of a Scully config file.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by SanderElias** [comment]
The check is there for a reason. We can't simply remove it.  It does prevent _really strange_ behavior in certain situations.
It does restart Scully within the correct folder if it is somehow confused. (PowerShell on windows, combined with  some other environmental things)
Without this check, Scully will just error out in a really weird way.
I'm not opposed to alternatives, but we can't remove the check.
I will close this PR, because for the above reasons.

**Comment by diminutivesloop** [comment]
I'd be interested to know under which scenarios this "really strange" behavior manifests. I was able to successfully build my Scully projects with this check removed so perhaps an option could be added to disable the check for projects where the check isn't necessary.

**Comment by diminutivesloop** [comment]
Also I noticed that the path to `scully.js` used for relaunching is incorrect and so the attempt to relaunch will always fail. It's `'./node_modules/@scullyio/scully/scully.js'` when it should be `'./node_modules/@scullyio/scully/src/scully.js'`. However when I fix the path it still fails to relaunch when in a subfolder and when I run it from the project root folder with Scully symlinked it just enters an infinite relaunch loop.

However if I simplify the check to just `if (!existsSync('./node_modules/@scullyio/scully/src/scully.js'))` then it works when Scully is symlinked but still prevents building from a subfolder. Would that be an acceptable solution?

**Comment by SanderElias** [comment]
@diminutivesloop  The really strange behavior happens on windows, with some more environmental issues.
IIRC it happens when using PowerShell inside a folder that had mixes casing somewhere inside the path.
Thanks for noticing the mishap in the relaunch. Due to tooling changes, that location did change. I thought I had updated them all.
If you can fix your issue, while still supporting the above use-case. I'm all in.
There should at least be an explanatory error for windows users. The strange reboot thing does actually fix the issue in the condition. I was never happy about it in the first place, but it is still something we need to do.

**Comment by diminutivesloop** [comment]
I have a solution that leaves the check intact so I'll open a PR with those changes. However I was unable to reproduce the Powershell error you described. I moved the project under the subpath `Mixed-Case-Path` but even when I tested with the relaunch code removed from `scully.ts` the build still succeeded in PowerShell.

**Comment by SanderElias** [comment]
@diminutivesloop I have _seen_ the behavior, but was unable to reproduce it. On different machines too, so it wasn't a 1-off problem The patch did fix it. Perhaps MS did fix a long-standing bug or something but I don't really want the one to figure it out.

**Pull request closed without merging**
