### PR TITLE
fix(ng-lib): getCurrent method needs decodeURI

### PR DESCRIPTION
**Pull request by stevermeister**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

## What is the current behavior?

Condition
```
curLocation === r.route.trim()
```
does not work because `curLocation` is not decoded, so there are some extra symbols there.

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by stevermeister** [comment]
in addition:
the issue works for `ng build --prod`, but does not for `ng build`

**Comment by SanderElias** [comment]
@stevermeister What problem does this solve? 
Can you provide some context?

**Comment by stevermeister** [comment]
@SanderElias yes, sure here you are:

https://scullyio.netlify.app/
if you click on the first post - you see the title
on the second - you are getting error in the console

and here is the code -
https://github.com/stevermeister/blog/blob/master/src/app/blog/blog.component.ts#L24

it does not work because URL in the browser is - `.../blog/2018/10/dutch-tax-income-calculator%253A-now-with-offline-mode`, but it tried to compare with `.../blog/2018/10/dutch-tax-income-calculator%3A-now-with-offline-mode`

**Comment by SanderElias** [comment]
Good catch

**Pull request merged**
