### PR TITLE
fix(doc): critical css and flash-prevention document added

### LINKED ISSUE #1135: Document the CriticalCSS/DiscountFlashPrevention plugins
## 🗄️ Docs report

Possibly two of the coolest plugins we've built in a while, and we haven't documented it.

### PR DESCRIPTION
**Pull request by sumitparakh**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Documentation

## What is the current behavior?

Issue Number: #1135 

## What is the new behavior?
1. Added new documentation markdown files for critical-css and flash-prevention plugins
2. Also fixed spelling mistake in [README](https://github.com/scullyio/scully/tree/main/libs/plugins/scully-plugin-critical-css) file of critical-css plugin and fixed a code snippet in it.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
Closes #1135

### CODE REVIEW

**Comment by SanderElias** [comment]
@sumitparakh can you add a link to the plugin's readme? 
https://github.com/scullyio/scully/tree/main/libs/plugins/scully-plugin-critical-css

**Comment by sumitparakh** [comment]
> @sumitparakh can you add a link to the plugin's readme? 
> https://github.com/scullyio/scully/tree/main/libs/plugins/scully-plugin-critical-css
> 

Sure

**Comment by sumitparakh** [comment]
Hi @SanderElias,

I've updated documentation for both critical-css and flash-prevention as per their README file. So I want to know if it is still relevant to add link to their README files in the documentation page?

**Comment by sumitparakh** [comment]
Not sure why checks failed 

image

**Comment by sumitparakh** [comment]
GitHub Actions service is down
https://www.githubstatus.com/

image

**Comment by SanderElias** [comment]
@sumitparakh Can you retract this PR and make a new one. Somehow it's damaged inside GitHub, and it won't pass any test for no reason. It's not the PR, it's something outside of our control.
I'm closing this one, please create a new one.

**Pull request closed without merging**
