### PR TITLE
fix(schematics):  ng add with project name

### PR DESCRIPTION
**Pull request by d-koppenhagen**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Other... Please describe: tests

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

before the it was possible that the `projectName` could have been empty and i n fact an error occured.
Fixes also all tests.

### CODE REVIEW

**Comment by jorgeucano** [comment]
‘defaultProject’ is a flag only... we never use into the files... please revert all the changes when use the text for the files

**Comment by d-koppenhagen** [comment]
But what’s the purpose of `defaultProject` as default value in the options? Shouldn’t this just by empty by default and then checking if the option is truthy (project name specified) and matches with the angular project?

**Comment by d-koppenhagen** [comment]
@jorgeucano can you check the changes again? I made some changes and added also some more tests for the `project` option usage.

**Comment by d-koppenhagen** [comment]
@jorgeucano can you check it again. I just resolved the conflicts with the master.

**Comment by jorgeucano** [comment]
I talked with @d-koppenhagen we will use this in the future but with some architecture changes... 
And for this i will close this pr!

**Pull request closed without merging**
