### PR TITLE
docs(showcase): adding AppsAtEase app to showcase

### PR DESCRIPTION
**Pull request by Sreekanth2108**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x ] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x ] Other... Please describe:
Updating showcase doc. Added appsastease.com to showcase list

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x ] No

### CODE REVIEW

**Comment by jorgeucano** [comment]
@GuzmanPI

**Comment by SanderElias** [comment]
Sreekanth2108 please make your logo available as a link, and not as an asset.
Don't mind the failing test, we will take care of that.

**Comment by Sreekanth2108** [comment]
@SanderElias Thank you
I removed file from assets and added link to it

**Comment by SanderElias** [comment]
Closed in favor of #660

**Pull request closed without merging**
