### PR TITLE
fix(ng-lib) normalize urlAfterRedirects before lastHandled comparison

### PR DESCRIPTION
**Pull request by jadengis**
Opening this PR as an attempt to resolve the caching issues that were effecting my first attempt at https://github.com/scullyio/scully/pull/1351.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

## What is the current behavior?
The url stored in `lastHandled` is normalized (fragments and queries removed). On NavigationEnd, this value is compared to `ev.urlAfterRedirects` which is not normalized and so `replaceContent` is called when it shouldn't be (routes to anchors on the same page).

Issue Number: #1350

## What is the new behavior?
Normalize `ev.urlAfterRedirects` before comparing to `lastHandled`.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
I didn't see a spec for the ScullyContent component, so I'm not sure what the best way to test this is.

### CODE REVIEW

**Review by SanderElias — DISMISSED** [review]

**Comment by jadengis** [comment]
@SanderElias I think I found the issue with the build. `package.json` has `v3.x.x` for `js-yaml` but `v4.x.x` for `@types/js-yaml` and upon inspecting the `index.d.ts` files there seems to be a mismatch between v3 and v4 (it appears as if v4 exposes a smaller api surface). I'm going to try rolling back to v3 for `@types/js-yaml` and see if that helps. Funny that this wasn't breaking before.

**Comment by SanderElias** [comment]
@jadengis I did update the code to work with V4? When you or is in, I'll check that out

**Comment by jadengis** [comment]
@SanderElias I'm not sure what to do here. The failing test failed trying to `npx ng new demo` and it looks like its one of the npm 7 dependency resolution errors. I'm pretty sure its unrelated to this change. What can I do to get it green? :pray:

**Review by SanderElias — APPROVED** [review]

**Comment by jadengis** [comment]
@SanderElias Hi Sander. So I updated the jest snapshots last about a week ago and after making that change it looks like all the tests are passing (I just ran `npm run test` locally and everything passed, and the jest tests and cypress e2e tests checks on this PR are also green). What's failing right now is this check https://github.com/scullyio/scully/pull/1366/checks?check_run_id=2685311994. It looks like `npx ng new demo --skipGit  --routing --style css --minimal --strict` is failing with to resolve peer dependencies with npm 7.

**Comment by SanderElias** [comment]
@jadengis yes, something changed in the latest version of the CLI. 
the CLI now officially un-supports node 15 and 1g 6. I'm in the process of removing those tests.

**Comment by jadengis** [comment]
:tada:

**Pull request merged**
