### PR TITLE
Add mobile styles to docs

### PR DESCRIPTION
**Pull request by donmckenna**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

## What is the current behavior?

No mobile styles for docs.

Issue Number: N/A

## What is the new behavior?

Docs now have mobile styles.

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by donmckenna** [comment]
Interesting. Fixed those conflicting files locally, but they're still conflicting.

**Comment by SanderElias** [comment]
@donmckenna I fixed the merge conflicts, and updated snapshots. Can you verify my merge didn't mess something up?

**Comment by donmckenna** [comment]
@SanderElias No, something is wrong. But I don't think your merge messed it up. Looks like those files weren't updated at all, there's a lot more code than the conflicts/solutions show. I'm looking into what I did on my end.

**Comment by donmckenna** [comment]
@SanderElias I see what is happening. I was mistaken, those green additions in your commit are actually the old pieces and don't belong where git is trying to put them.

So actually, the correct state of those 3 files is the left side, without the additions. Changing the files to not include those most recent additions should be fine.

This is correct, for example:

image

You can also see the updated padding in `intro.component.css` is directly inside a media query, which makes no sense:

image

And in `nav-header.component.css` you can also see `nav.scullyio-nav-header ul li.icon a` actually starts on line `202` and has the correct associated media queries. Whereas the one which starts on line `265` is a duplicate and incomplete.

**Comment by SanderElias** [comment]
@jorgeucano I'm ok with this PR, and will fix the MC and merge when you approve

**Pull request closed without merging**
