### PR TITLE
refactor/cleanup: scully schematics

### PR DESCRIPTION
**Pull request by d-koppenhagen**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

- use existing utils to read and write `package.json` config parts
- split logic into smaller chainable functions
- provide aditional tests
- remove unused schema option `project`

### CODE REVIEW

**Comment by d-koppenhagen** [comment]
https://github.com/scullyio/scully/pull/176 should be merged first

**Comment by aaronfrost** [comment]
@jorgeucano I am going to let you review this.

**Comment by jorgeucano** [comment]
@d-koppenhagen i will test this today and check all the test in angular !

**Comment by d-koppenhagen** [comment]
Perfect!

**Comment by jorgeucano** [comment]
remove the prompt and i will approve :)

**Comment by d-koppenhagen** [comment]
@jorgeucano done :)

**Comment by jorgeucano** [comment]
This branch has conflicts that must be resolved :) @d-koppenhagen fix this and i will merge

**Comment by d-koppenhagen** [comment]
@jorgeucano #176 has to be merged first.

**Comment by d-koppenhagen** [comment]
@jorgeucano done.

**Comment by jorgeucano** [comment]
done, thanks for all your work :D

**Pull request merged**
