### PR TITLE
docs(lib): instruct user to have Angular CLI generate the routing.

### PR DESCRIPTION
**Pull request by gerhardboer**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Other... Please describe: Documentation

## What is the current behavior?

Issue Number: https://github.com/scullyio/scully/issues/358

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by SanderElias** [comment]
@gerhardboer If you sign the CLA, we can merge your proposal!

**Comment by gerhardboer** [comment]
> @gerhardboer If you sign the CLA, we can merge your proposal!

I've signed it on multiple devices now, and when i check it says: "You have signed the CLA for multiple repositories or organizations".

I don't know why the check fails..

**Comment by Villanuevand** [comment]
@SanderElias  / @gerhardboer  
Let me check what's going on with the Bot... 

I will let you  soon....

**Comment by Villanuevand** [comment]
@gerhardboer  / @SanderElias 
We have a very weird edge case here. Checking CLA Assistence you already signed as you say.

---
Captura de Pantalla 2020-03-11 a la(s) 17 58 19

I send a new PR's revision, let's wait a bit...

**Comment by Villanuevand** [comment]
Hey guys!  @gerhardboer  @SanderElias 

Nothing happen with this issue... 
I think we need to try closing the PR and create another one. 

What do you think?

**Comment by gerhardboer** [comment]
Sounds like a plan :)

**Comment by Villanuevand** [comment]
@gerhardboer  Im going to proceed!  
See you in the next PR

**Pull request closed without merging**
