### PR TITLE
fix: make sure devDependencies are marked as such

### PR DESCRIPTION
**Pull request by beeman**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [x] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

## What is the current behavior?

This should be a start to tackle this issue:

Issue Number: #88 

## What is the new behavior?

Dependencies needed only during development are moved to the `devDependencies` object. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

I checked these pages and found that almost none of the devDependencies are marked as such:

https://www.npmjs.com/package/@scullyio/scully?activeTab=dependencies
https://www.npmjs.com/package/@scullyio/init?activeTab=dependencies

There might be more deps that can be moved, but this should be a good start.

### CODE REVIEW

**Comment by SanderElias** [comment]
@beeman, we need to talk this one through. As Scully is a dev-time tool, arent all of them devDepedencies?
Also ,the top-level package.json is actually not being distributed to anywhere, but just four our own development mono-repo. That means that everything in there is a devDepdency right?

**Comment by beeman** [comment]
@SanderElias scully being a dev-time tool is not relevant here. 

We should only list the dependencies that are needed in runtime in the `dependencies` object, the rest (what's needed to build scully itself) goes into `devDependencies`. This keeps the fotoprint small and prevents downloading and installing unneeded deps.

With regards to the top-level package, as it's not distributed it doesn't really matter but you are right, they could all be devDependencies.

**Comment by aaronfrost** [comment]
This LGTM, but deferring to @SanderElias for approval.

**Comment by SanderElias** [comment]
> We should only list the dependencies that are needed in runtime in the dependencies object, the rest (what's needed to build scully itself) goes into devDependencies. This keeps the fotoprint small and prevents downloading and installing unneeded deps.

You are right!

**Pull request merged**
