### PR TITLE
adding scanRoutes to detect new blog path

### PR DESCRIPTION
**Pull request by willi84**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [x] Other... Please describe: docs

## What is the current behavior?

When creating new route for blog the route is not generated without scanRoutes. Can be confusing for newbies.

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by SanderElias** [comment]
@willi84 The `--scanRoutes` is only needed if you alter the angular app, not for adding additional blogs.
Perhaps you should add a few lines of documentation to explain this, to prevent developers from mindless slapping on `--scanRoutes` 
After all, we made it optional for the reason that scanning the routes can take a significant amount of time in some projects.

**Comment by SanderElias** [comment]
@willi84 Can you respond to the question?

**Comment by willi84** [comment]
@SanderElias will think about it.

**Comment by willi84** [comment]
Hi Sanders, 

sry, I was totally busy.

How about adding at the end a troubleshooting section?

#Troubleshooting
If the route for your new blog post is not recognized, please use **ONCE** the following command to scan a new route:

```bash
npm run scully -- --scanRoutes
```

**Pull request closed without merging**
