### PR TITLE
feat(schematics): allow specify a file extension when creating a post

### PR DESCRIPTION
**Pull request by d-koppenhagen**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #213 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by d-koppenhagen** [comment]
To got all tests working, https://github.com/scullyio/scully/pull/236 is needed

**Comment by SanderElias** [comment]
Looks good to me, but @jorgeucano is in charge of the schematics.

**Comment by aaronfrost** [comment]
@jorgeucano check out this PR. This is all you. It looks good to me. But... want to make sure you are down.

**Comment by jorgeucano** [comment]
I talked with @d-koppenhagen we will use this in the future but with some architecture changes... 
And for this i will close this pr!

**Pull request closed without merging**
