### PR TITLE
feat: Sentry logs

### PR DESCRIPTION
**Pull request by PatrickJS**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Other... Please describe:

## What is the current behavior?
no error logging for the cli or docs

Issue Number: N/A

## What is the new behavior?
error logging for the docs and cli

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information
fixes https://github.com/scullyio/scully/issues/783

### CODE REVIEW

**Comment by amycdurbin** [comment]
@aaronfrost should we make this optional instead of required?

**Comment by aaronfrost** [comment]
@amycdurbin should we make WHAT mandatory? That they opt into errors? Yes. It is not required to get permission for errors (I was told by Patrick). It is, however, required to get permission for telemetry data. So these errors are not telemetry. So let's do it.

Also, let's get this merged already... I want to see the errors that the users are seeing. We are wasting daylight by not merging this PR. Get it done already.

**Comment by amycdurbin** [comment]
> @amycdurbin should we make WHAT mandatory? That they opt into errors? Yes. It is not required to get permission for errors (I was told by Patrick). It is, however, required to get permission for telemetry data. So these errors are not telemetry. So let's do it.
> 
> Also, let's get this merged already... I want to see the errors that the users are seeing. We are wasting daylight by not merging this PR. Get it done already.

@SanderElias please see Frosty's response.

**Comment by SanderElias** [comment]
@aaronfrost I'm pretty sure collecting any data (including errors) from a user's system goes right into GRPD.
Or at least it will be frowned upon, and lead to questions that are easily avoided.

**Pull request merged**
